In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import sklearn

from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from mpl_toolkits.mplot3d import Axes3D

%matplotlib notebook


In [55]:
x_dim = 3
y_dim = 2
n_samples = 100

X = np.asmatrix(np.zeros((n_samples,x_dim)))
Y = np.asmatrix(np.zeros((n_samples,y_dim)))

# display(x,y)

In [78]:
for n in range(n_samples):
    for i in range(x_dim):
        X[n,i] = round(np.random.rand(),3)
    for j in range(y_dim):
        Y[n,j] = round(np.random.rand(),3)

data = np.hstack([X,Y])
display(data)

matrix([[0.335, 0.431, 0.82 , 0.341, 0.24 ],
        [0.086, 0.611, 0.252, 0.794, 0.326],
        [0.868, 0.205, 0.365, 0.643, 0.87 ],
        [0.61 , 0.494, 0.373, 0.924, 0.2  ],
        [0.061, 0.269, 0.414, 0.55 , 0.34 ],
        [0.653, 0.959, 0.04 , 0.248, 0.741],
        [0.764, 0.449, 0.439, 0.071, 0.712],
        [0.114, 0.574, 0.532, 0.54 , 0.736],
        [0.336, 0.334, 0.695, 0.571, 0.478],
        [0.101, 0.351, 0.756, 0.198, 0.38 ],
        [0.253, 0.932, 0.647, 0.089, 0.904],
        [0.356, 0.34 , 0.191, 0.686, 0.932],
        [0.04 , 0.548, 0.719, 0.45 , 0.936],
        [0.531, 0.499, 0.784, 0.473, 0.049],
        [0.993, 0.128, 0.849, 0.192, 0.699],
        [0.343, 0.795, 0.396, 0.11 , 0.898],
        [0.17 , 0.642, 0.501, 0.237, 0.033],
        [0.386, 0.51 , 0.948, 0.749, 0.207],
        [0.426, 0.157, 0.993, 0.426, 0.227],
        [0.159, 0.874, 0.647, 0.097, 0.875],
        [0.545, 0.867, 0.477, 0.137, 0.055],
        [0.492, 0.67 , 0.449, 0.62 , 0.391],
        [0

In [69]:
x = np.zeros((n_samples,x_dim))
y = np.zeros((n_samples,y_dim))

for n in range(n_samples):
    for i in range(x_dim):
        x[n,i] = round(np.random.rand(),3)
    for j in range(y_dim):
        y[n,j] = round(np.random.rand(),3)

data_2 = np.hstack([x,y])
display(data_2,data_2.shape)

array([[0.098, 0.808, 0.819, 0.246, 0.553],
       [0.823, 0.56 , 0.237, 0.129, 0.729],
       [0.518, 0.271, 0.178, 0.105, 0.535],
       [0.775, 0.178, 0.713, 0.442, 0.805],
       [0.277, 0.7  , 0.568, 0.967, 0.752],
       [0.355, 0.201, 0.871, 0.876, 0.459],
       [0.123, 0.838, 0.243, 0.664, 0.126],
       [0.581, 0.882, 0.745, 0.855, 0.015],
       [0.32 , 0.943, 0.782, 0.178, 0.374],
       [0.065, 0.981, 0.519, 0.27 , 0.323],
       [0.492, 0.171, 0.887, 0.16 , 0.623],
       [0.246, 0.09 , 0.158, 0.838, 0.193],
       [0.59 , 0.309, 0.37 , 0.349, 0.609],
       [0.47 , 0.477, 0.916, 0.8  , 0.587],
       [0.743, 0.762, 0.646, 0.277, 0.885],
       [0.773, 0.573, 0.913, 0.479, 0.656],
       [0.82 , 0.607, 0.333, 0.015, 0.452],
       [0.338, 0.916, 0.872, 0.229, 0.143],
       [0.972, 0.486, 0.612, 0.745, 0.717],
       [0.162, 0.427, 0.138, 0.837, 0.92 ],
       [0.715, 0.879, 0.263, 0.358, 0.026],
       [0.959, 0.148, 0.059, 0.722, 0.322],
       [0.551, 0.661, 0.784, 0.9

(100, 5)

In [73]:
x = np.zeros((n_samples,x_dim))
y = np.zeros((n_samples,y_dim))

for n in range(n_samples):
    x[n,:] = np.random.rand(x_dim).round(3)
    y[n,:] = np.random.rand(y_dim).round(3)

data_3 = np.hstack([x,y])

display(data_3)

array([[0.002, 0.487, 0.66 , 0.92 , 0.981],
       [0.452, 0.373, 0.327, 0.014, 0.827],
       [0.045, 0.671, 0.291, 0.837, 0.008],
       [0.2  , 0.854, 0.112, 0.534, 0.69 ],
       [0.546, 0.287, 0.982, 0.915, 0.997],
       [0.827, 0.385, 0.369, 0.684, 0.237],
       [0.758, 0.878, 0.246, 0.896, 0.306],
       [0.976, 0.28 , 0.757, 0.817, 0.989],
       [0.852, 0.722, 0.677, 0.419, 0.836],
       [0.54 , 0.129, 0.126, 0.302, 0.754],
       [0.798, 1.   , 0.293, 0.039, 0.139],
       [0.721, 0.607, 0.631, 0.775, 0.968],
       [0.144, 0.475, 0.899, 0.483, 0.993],
       [0.883, 0.276, 0.048, 0.916, 0.407],
       [0.678, 0.421, 0.234, 0.957, 0.841],
       [0.974, 0.499, 0.333, 0.61 , 0.045],
       [0.144, 0.24 , 0.517, 0.611, 0.48 ],
       [0.243, 0.068, 0.475, 0.794, 0.249],
       [0.037, 0.792, 0.364, 0.698, 0.592],
       [0.127, 0.986, 0.265, 0.789, 0.402],
       [0.95 , 0.312, 0.648, 0.158, 0.884],
       [0.257, 0.255, 0.378, 0.475, 0.686],
       [0.015, 0.895, 0.712, 0.9